
import type { NavItem, FeatureCardItem } from '@/types';
import {
  Home,
  Gamepad2,
  Brain,
  Orbit,
  Puzzle,
  Sigma,
  Calculator as CalculatorIcon, 
  TestTubeDiagonal, 
  Scale,
  BookOpen,
  Settings,
  FileCode, 
  Target, 
  SearchCode, 
  Wrench, 
  ClipboardCheck, 
  BarChart3, 
  FileJson,
  LineChart,
  FunctionSquare,
  Code as CodeIcon, 
  Binary,
  Zap,
  BrainCircuit, // Icon for Algorithm Arena
  BarChartHorizontal, // Icon for Sorting
  Search, // Icon for Searching
  GitFork, // Icon for Graph Traversal
  Repeat, // Icon for Recursion
  Users, // Icon for Game Theory
} from 'lucide-react';

export const navItems: NavItem[] = [
  {
    title: 'Home',
    href: '/',
    icon: Home,
  },
  {
    title: 'Games',
    href: '#', 
    icon: Gamepad2,
    subItems: [
      {
        title: 'Binary Converter',
        href: '/binary-game',
        icon: Brain,
        description: 'Learn binary with an 8/16-bit interactive game.',
      },
      {
        title: 'Unit Circle Explorer',
        href: '/unit-circle',
        icon: Orbit,
        description: 'Explore angles, radians, and trig functions.',
      },
      {
        title: 'Hex Boxes Challenge',
        href: '/hex-boxes',
        icon: Puzzle,
        description: 'Convert decimal to two-digit hex values.',
      },
      {
        title: 'Fraction Duel',
        href: '/quick-math/fraction-duel',
        icon: TestTubeDiagonal,
        description: 'Test your fraction arithmetic skills in a duel!',
      },
      {
        title: 'Ratio Scales',
        href: '/quick-math/ratio-scales',
        icon: Scale,
        description: 'Balance weights to understand ratios.',
      },
    ],
  },
  {
    title: 'Tools',
    href: '#', 
    icon: Settings, 
    subItems: [
       {
        title: 'Calculus Playground',
        href: '/calculus-playground',
        icon: Sigma,
        description: 'Visualize functions, derivatives, and integrals.',
      },
      {
        title: 'Prime Tester',
        href: '/tools/prime-tester',
        icon: Binary,
        description: 'Test numbers for primality and find factors.',
      },
      {
        title: 'Math Battle',
        href: '/tools/math-battle',
        icon: Zap,
        description: 'Quick fire math problems against the clock.',
      },
      {
        title: 'Algorithm Arena',
        href: '/tools/algorithm-arena',
        icon: BrainCircuit,
        description: 'Explore algorithms and game theory interactively.',
        subItems: [ // Nested subItems for Algorithm Arena
          {
            title: 'Sorting Visualizer',
            href: '/tools/algorithm-arena/sorting',
            icon: BarChartHorizontal,
            description: 'Visualize sorting algorithms like Bubble Sort, Merge Sort.',
          },
          {
            title: 'Searching Visualizer',
            href: '/tools/algorithm-arena/searching',
            icon: Search,
            description: 'See how Binary Search and Linear Search work.',
          },
          {
            title: 'Graph Traversal',
            href: '/tools/algorithm-arena/graph-traversal',
            icon: GitFork,
            description: 'Explore BFS, DFS, Dijkstra’s algorithm.',
          },
          {
            title: 'Recursion Visualizer',
            href: '/tools/algorithm-arena/recursion',
            icon: Repeat,
            description: 'Understand Factorial, Fibonacci, Tower of Hanoi.',
          },
          {
            title: 'Game Theory Playground',
            href: '/tools/algorithm-arena/game-theory',
            icon: Users,
            description: 'Simulate Prisoner\'s Dilemma and other scenarios.',
          },
        ]
      },
    ],
  },
  {
    title: 'Lessons',
    href: '/lessons', 
    icon: BookOpen,
    disabled: false, 
    subItems: [
      {
        title: 'Python Foundations',
        href: '/lessons/python-foundations',
        icon: FileCode,
        description: 'Learn core Python concepts step by step.',
      },
      {
        title: 'JavaScript Essentials',
        href: '/lessons/javascript-essentials',
        icon: CodeIcon, 
        description: 'Master fundamental JavaScript concepts.',
      }
    ]
  },
];

export const featureCards: FeatureCardItem[] = [
  {
    title: 'Binary Converter Game',
    description: 'Master binary numbers with our interactive 8-bit and 16-bit converter game. Toggle bits, see instant decimal and hex conversions, and test your skills in game mode!',
    href: '/binary-game',
    icon: Brain,
    imageSrc: 'https://picsum.photos/seed/binarygame/600/400',
    imageAlt: 'Binary game interface with toggles and lights',
    dataAiHint: 'binary code',
    ctaLabel: 'Play Now',
  },
  {
    title: 'Python Foundations',
    description: 'Embark on your Python journey! Learn the fundamentals with interactive lessons, a code sandbox, and gamified challenges.',
    href: '/lessons/python-foundations',
    icon: FileCode,
    imageSrc: 'https://picsum.photos/seed/pythoncourse/600/400',
    imageAlt: 'Python code on a screen',
    dataAiHint: 'python programming',
    ctaLabel: 'Start Learning',
  },
   {
    title: 'JavaScript Essentials',
    description: 'Dive into JavaScript! Interactive lessons, a live code sandbox, and practical exercises to build your web development skills.',
    href: '/lessons/javascript-essentials',
    icon: CodeIcon,
    imageSrc: 'https://picsum.photos/seed/javascriptcourse/600/400',
    imageAlt: 'JavaScript code on a screen',
    dataAiHint: 'javascript programming',
    ctaLabel: 'Learn JS',
  },
  {
    title: 'Algorithm Arena',
    description: 'Explore sorting, searching, graph traversal, recursion, and game theory with interactive visualizations and simulations. Understand algorithms step-by-step.',
    href: '/tools/algorithm-arena',
    icon: BrainCircuit,
    imageSrc: 'https://picsum.photos/seed/algorithmmarena/600/400',
    imageAlt: 'Abstract representation of algorithms and logic flows',
    dataAiHint: 'algorithms logic',
    ctaLabel: 'Explore Arena',
  },
  {
    title: 'Interactive Unit Circle',
    description: 'Explore the unit circle dynamically. Drag the angle, see radians, degrees, and trigonometric values (sin, cos, tan) update in real-time. Visualize the linked sine wave.',
    href: '/unit-circle',
    icon: Orbit,
    imageSrc: 'https://picsum.photos/seed/unitcircletool/600/400',
    imageAlt: 'Unit circle diagram with sine wave',
    dataAiHint: 'math diagram',
    ctaLabel: 'Explore Circle',
  },
  {
    title: 'Calculus Playground',
    description: 'Visualize calculus concepts. Input functions, explore graphs, derivatives (as tangent lines), and integrals (area under curve) with an interactive slider and customizable graph bounds.',
    href: '/calculus-playground',
    icon: Sigma,
    imageSrc: 'https://picsum.photos/seed/calculustool/600/400',
    imageAlt: 'Graph of a function with tangent line and shaded area',
    dataAiHint: 'calculus graph',
    ctaLabel: 'Start Plotting',
  },
  {
    title: 'Prime Number Tester',
    description: 'Test numbers for primality, find their factors, and explore sequences of prime numbers. A great tool for understanding number theory basics.',
    href: '/tools/prime-tester',
    icon: Binary,
    imageSrc: 'https://picsum.photos/seed/primetester/600/400',
    imageAlt: 'Abstract representation of prime numbers or number grid',
    dataAiHint: 'prime numbers math',
    ctaLabel: 'Test Primes',
  },
  {
    title: 'Math Battle Game',
    description: 'Challenge your mental math skills! Solve a variety of arithmetic and logic problems against the clock. Improve your speed and accuracy.',
    href: '/tools/math-battle',
    icon: Zap,
    imageSrc: 'https://picsum.photos/seed/mathbattle/600/400',
    imageAlt: 'Dynamic display of math problems and scores',
    dataAiHint: 'math game quiz',
    ctaLabel: 'Start Battle',
  },
  {
    title: 'Hex Boxes Challenge',
    description: 'Learn hexadecimal conversion by converting decimal numbers (0-255) to two-digit hex values. Select digits from a grid and test your understanding in challenge or learn mode.',
    href: '/hex-boxes',
    icon: Puzzle,
    imageSrc: 'https://picsum.photos/seed/hexgame/600/400',
    imageAlt: 'Hexadecimal digit selection grid',
    dataAiHint: 'hexadecimal code',
    ctaLabel: 'Play Hex Game',
  },
  {
    title: 'Fraction Duel',
    description: 'Challenge your fraction arithmetic! Solve expressions by choosing the correct simplified answer from multiple choices. Difficulty increases with each turn.',
    href: '/quick-math/fraction-duel',
    icon: TestTubeDiagonal,
    imageSrc: 'https://picsum.photos/seed/fractiongame/600/400',
    imageAlt: 'Fraction expression with multiple choice answers',
    dataAiHint: 'fraction math game',
    ctaLabel: 'Start Duel',
  },
  {
    title: 'Ratio Scales',
    description: 'Balance weights on virtual scales to intuitively understand ratios and proportions. Experiment with different weights and see how equivalent ratios are formed.',
    href: '/quick-math/ratio-scales',
    icon: Scale,
    imageSrc: 'https://picsum.photos/seed/ratiogame/600/400',
    imageAlt: 'Balance scale with weights',
    dataAiHint: 'balance scale math',
    ctaLabel: 'Explore Ratios',
  },
  {
    title: 'Python: Output Match',
    description: 'Match Python code snippets to their correct output. A fun way to test your understanding of Python execution.',
    href: '/lessons/python-foundations/output-match',
    icon: Target,
    imageSrc: 'https://picsum.photos/seed/pyoutputchallenge/600/400',
    imageAlt: 'Python code and output comparison',
    dataAiHint: 'python coding',
    isComingSoon: false, 
    ctaLabel: 'Try Challenge',
  },
  {
    title: 'Python: Syntax Spotter',
    description: 'Can you spot the syntax errors? Sharpen your Python debugging skills by identifying mistakes in code.',
    href: '/lessons/python-foundations/syntax-spotter',
    icon: SearchCode,
    imageSrc: 'https://picsum.photos/seed/pysyntaxchallenge/600/400',
    imageAlt: 'Python code with highlighted errors',
    dataAiHint: 'python syntax',
    isComingSoon: false, 
    ctaLabel: 'Spot Errors',
  },
  {
    title: 'Python: Debug It!', 
    description: 'Fix broken Python code! Apply your knowledge to debug real-world-like scenarios and make the code run.',
    href: '/lessons/python-foundations/debug-it',
    icon: Wrench,
    imageSrc: 'https://picsum.photos/seed/pydebugchallenge/600/400',
    imageAlt: 'Python code with debugging tools',
    dataAiHint: 'python debugging code',
    isComingSoon: false, 
    ctaLabel: 'Debug Code',
  },
  {
    title: 'JS: Output Match',
    description: 'Match JavaScript code snippets to their correct console output. Test your JS execution knowledge.',
    href: '/lessons/javascript-essentials/output-match',
    icon: Target, 
    imageSrc: 'https://picsum.photos/seed/jsoutputchallenge/600/400',
    imageAlt: 'JavaScript code and console output comparison',
    dataAiHint: 'javascript coding',
    isComingSoon: false,
    ctaLabel: 'Try JS Challenge',
  },
  {
    title: 'JS: Syntax Spotter',
    description: 'Spot syntax errors in JavaScript code. A great way to improve your attention to detail.',
    href: '/lessons/javascript-essentials/syntax-spotter',
    icon: SearchCode,
    imageSrc: 'https://picsum.photos/seed/jssyntaxchallenge/600/400',
    imageAlt: 'JavaScript code with error highlighting',
    dataAiHint: 'javascript syntax',
    isComingSoon: false,
    ctaLabel: 'Spot JS Errors',
  },
  {
    title: 'JS: Debug It!',
    description: 'Fix buggy JavaScript code! Use the in-browser sandbox to test and correct the snippets.',
    href: '/lessons/javascript-essentials/debug-it',
    icon: Wrench,
    imageSrc: 'https://picsum.photos/seed/jsdebugchallenge/600/400',
    imageAlt: 'JavaScript code in a debugger interface',
    dataAiHint: 'javascript debugging',
    isComingSoon: false,
    ctaLabel: 'Debug JS Code',
  },
  {
    title: 'Data Structures Visualizer',
    description: 'Coming soon! Interactive visualizations of common data structures like arrays, linked lists, trees, and graphs. Understand their operations and complexities.',
    href: '#', 
    icon: FileJson,
    imageSrc: 'https://picsum.photos/seed/datastructuresvis/600/400',
    imageAlt: 'Abstract representation of data structures',
    dataAiHint: 'data structures',
    isComingSoon: true,
    ctaLabel: 'Coming Soon',
  },
];

export const siteConfig = {
  name: "Plenty of π",
  description: "Interactive tools and engaging lessons to make learning math and computer science fun and accessible.",
  url: "https://example.com", 
  ogImage: "https://example.com/og.jpg", 
  links: {
    twitter: "https://twitter.com/example", 
    github: "https://github.com/example/plenty-of-pi", 
  },
  navItems, 
  featureCards, 
};

export type SiteConfig = typeof siteConfig;
